#!/usr/bin/env bash

cp .env.dev.sample .env.dev

docker-compose build

docker-compose run --rm rails bundle exec rails new . --force --database=postgresql --skip-turbolinks --skip-git --skip-test --webpack=react

cp -f template/database.yml config/database.yml
sed -i ".bak" -e "s/host: localhost/host: 0.0.0.0/g" config/webpacker.yml

docker-compose run --rm rails bundle exec spring binstub --all
